project:
  type: book
  output-dir: GUIDEBOOK
  
  
book:
  title: "NP Trends Survey Data Preparation Guide"
  output-file: "np-trends-book"
  author: 
    - "Thiya"
    - "Jesse Lecy"
    - "Hannah Martin"
  date: last-modified
  sidebar: 
    style: "docked"
    background: "#1273A1"  
  chapters:
    - index.qmd
    - 0_01-r-setup.qmd
    - 0_02-create-dd-files.qmd
    - part: 2_00-YEAR-TWO.qmd
      chapters: 
      - 2_01-recoding-rules-y2.qmd
      - 2_02-fix-demographics-y2.qmd
      - 2_03-summarize-responses-y2.qmd
      - 2_04-response-rates-y2.qmd
    - part: 3_00-YEAR-THREE.qmd
      chapters: 
      - 3_01-recoding-rules-y3.qmd
      - 3_02-fix-demographics-y3.qmd
      - 3_03-summarize-responses-y3.qmd
    - part: 4_00-GEOCODING.qmd
      chapters:
      - 4_01-validating-addresses.qmd
      - 4_02-geocoding-addresses.qmd
      - 4_03-adding-geographies.qmd
    - part: 5_00-WEIGHTS.qmd
    - 99-references.qmd
      

bibliography: references.bib

format:
  html:
    theme: lux
    highlight-style: solarized
    css: style.css
    grid:
      sidebar-width: 225px
      body-width: 900px
      margin-width: 400px
      gutter-width: 100px
  # pdf: 
  #   documentclass: scrbook

editor: visual

