# Params for NP Trends survey analysis

# Path to raw year 4 survey data
nptrends_y4_raw_path <- "Y:/CNP/Generosity Commission/Year 4/Restricted Dataset/RESTRICTED_Y4.csv"
nptrends_y5_raw_path <- "Y:/CNP/Generosity Commission/Year 5/Restricted Dataset/RESTRICTED_Y5.csv"

# Variable names needed for analysis
survey_analysis_vars <- c(
  "SizeStrata",
  "ntmaj12",
  "census_urban_area",
  "CensusRegion4",
  "year4wt",
  "stateweight",
  "year5wt",
  "TotRev_clean",
  "FinanceChng_Reserves",
  "FinanceChng_TotExp",
  "FinanceChng_Salaries",
  "FinanceChng_Benefits",
  "FinanceChng_TotRent",
  "FinanceChng_TotTech",
  "GeoAreas_Local",
  "GeoAreas_MultipleLocal",
  "GeoAreas_RegionalWithin",
  "GeoAreas_State",
  "GeoAreas_RegionalAcross",
  "GeoAreas_MultipleState",
  "GeoAreas_National",
  "GeoAreas_International",
  "ProgDem_BelowFPL",
  "ProgDem_Disabled",
  "ProgDem_Veterans",
  "ProgDem_LGBTQ",
  "ProgDem_Foreign",
  "ProgDem_Latinx",
  "ProgDem_Black",
  "ProgDem_Indigenous",
  "ProgDem_Asian",
  "ProgDem_Men",
  "ProgDem_Women",
  "ProgDem_Nonbinary",
  "ProgDem_Children",
  "ProgDem_YoungAdults",
  "ProgDem_Adults",
  "ProgDem_Elders",
  "PplSrv_NumServed_NA_X",
  "PplSrv_NumWait",
  "PplSrv_NumWait_NA_X",
  "PrgSrvc_Suspend",
  "PrgSrvc_Amt_Srvc",
  "PrgSrvc_Amt_Num",
  "Dmnd_NxtYear",
  "FndRaise_DnrBlw250",
  "FndRaise_DnrAbv250",
  "FndRaise_DAF_Rcv",
  "FndRaise_PFGrnt_Rcv",
  "FndRaise_Corp_Found_Grnt_Rcv",
  "FndRaise_CFGrnt_Rcv",
  "CARES_Rcv",
  "PrgSrvc_Amt_Fee",
  "FndRaise_TotExp",
  "FndRaise_TotDigAppeal",
  "FndRaise_TotDirMail",
  "FndRaise_TotVirtEvent",
  "FndRaise_TotInPersEvent",
  "PercentDem_Women_Staff",
  "Staff_RegVlntr_2023",
  "Staff_RegVlntr_NA",
  "Staff_EpsdVltnr_2023",
  "Staff_EpsdVltnr_NA",
  "PercentDem_Women_Board",
  "PercentDem_LGBTQ_Board",
  "PercentDem_Disabled_Board",
  "PercentDem_Young_Board",
  "PercentDem_ReceivedServices_Board",
  "PercentDem_POC_Staff",
  "PercentDem_LGBTQ_Staff",
  "PercentDem_Disabled_Staff",
  "PercentDem_Young_Staff",
  "PercentDem_ReceivedServices_Staff",
  "Staff_Boardmmbr_2023",
  "Staff_Boardmmbr_NA",
  "PercentDem_POC_Board",
  "CEOrace",
  "Dem_CEO_LGBTQ",
  "Dem_CEO_Disabled",
  "Dem_CEO_Age",
  "BChairrace",
  "Dem_BChair_LGBTQ",
  "Dem_BChair_Disabled",
  "Dem_BChair_Age",
  "Staff_Fulltime_2023",
  "Staff_Fulltime_NA",
  "Staff_Parttime_2023",
  "Staff_Parttime_NA",
  "CEOgender_Man",
  "CEOgender_Woman",
  "CEOgender_NB",
  "BChairgender_Man",
  "BChairgender_Woman",
  "BChairgender_NB",
  "TotExp",
  "Reserves_Est",
  "Reserves_NA_X",
  "PercentDon_Tot",
  "PercentDAF_Tot",
  "PercentPriv_Tot",
  "PercentCorp_Tot",
  "PercentGov",
  "PercentEarned",
  "FndRaise_LocGvtGrnt_Rcv",
  "FndRaise_StateGvtGrnt_Rcv",
  "FndRaise_FedGvtGrnt_Rcv",
  "FndRaise_LocGvtLn_Rcv",
  "FndRaise_StateGvtLn_Rcv",
  "FndRaise_FedGvtLn_Rcv",
  "FndRaise_LocGvtCntrct_Rcv",
  "FndRaise_StateGvtCntrct_Rcv",
  "FndRaise_FedGvtCntrct_Rcv",
  "FndRaise_FeeOth_Rcv",
  "FndRaise_FeeMed_Rcv",
  "FndRaise_Tribal_Rcv",
  "FndRaise_GovOth_Rcv",
  "FndRaise_DAF_Grnt_Chng",
  "FndRaise_Priv_Grnt_Chng",
  "FndRaise_Corp_Grnt_Chng",
  "Staff_RegVlntr_2024",
  "Staff_EpsdVltnr_2024",
  "Staff_Boardmmbr_2024",
  "Staff_Fulltime_2024",
  "Staff_Parttime_2024"
)

# Questions with 5 possible answers: Significant decrease, decrease, stay the same, increase, significant increase
multi_select_cols <- c(
  "FinanceChng_TotExp",
  "FinanceChng_Salaries",
  "FinanceChng_Benefits",
  "FinanceChng_TotRent",
  "FinanceChng_TotTech",
  "PrgSrvc_Amt_Srvc",
  "PrgSrvc_Amt_Num",
  "PrgSrvc_Amt_Fee",
  "FndRaise_TotExp",
  "FndRaise_TotDigAppeal",
  "FndRaise_TotDirMail",
  "FndRaise_TotVirtEvent",
  "FndRaise_TotInPersEvent"
)

# Questions with 2 possible answers: Received, did not receive
binary_rcv_cols <- c(
  "FndRaise_DAF_Rcv",
  "FndRaise_PFGrnt_Rcv",
  "FndRaise_Corp_Found_Grnt_Rcv",
  "FndRaise_CFGrnt_Rcv",
  "CARES_Rcv"
)

# Government funding questions
gvt_fndraise_vars <- c(
  "FndRaise_LocGvtGrnt_Rcv",
  "FndRaise_StateGvtGrnt_Rcv",
  "FndRaise_FedGvtGrnt_Rcv",
  "FndRaise_LocGvtLn_Rcv",
  "FndRaise_StateGvtLn_Rcv",
  "FndRaise_FedGvtLn_Rcv",
  "FndRaise_LocGvtCntrct_Rcv",
  "FndRaise_StateGvtCntrct_Rcv",
  "FndRaise_FedGvtCntrct_Rcv",
  "FndRaise_FeeOth_Rcv",
  "FndRaise_FeeMed_Rcv",
  "FndRaise_Tribal_Rcv",
  "FndRaise_GovOth_Rcv",
  "FndRaise_DAF_Grnt_Chng",
  "FndRaise_Priv_Grnt_Chng",
  "FndRaise_Corp_Grnt_Chng"
)

# Questions valid for 2024 but not 2025
qns_invalid_2024 <- c(
  "PercentDon_Tot",
  "PercentGov",
  "PercentEarned"
)

# Demographic percentage questions
percentdem_vars <- c(
  "PercentDem_Women_Board",
  "PercentDem_LGBTQ_Board",
  "PercentDem_Disabled_Board",
  "PercentDem_Young_Board",
  "PercentDem_ReceivedServices_Board",
  "PercentDem_POC_Staff",
  "PercentDem_LGBTQ_Staff",
  "PercentDem_Disabled_Staff",
  "PercentDem_Young_Staff",
  "PercentDem_ReceivedServices_Staff",
  "PercentDem_POC_Board"
)

# Number of staff questions
numstaff_ls <- c(
  "Staff_Fulltime_2023" = "Staff_Fulltime_NA",
  "Staff_Fulltime_2024" = "Staff_Fulltime_NA",
  "Staff_Parttime_2023" = "Staff_Parttime_NA",
  "Staff_Parttime_2024" = "Staff_Parttime_NA"
)