# Internal data objects used for data processing and validation

# metricsMaster table for validation
# metricsMaster <- gsheet::gsheet2tbl(metricsMaster_path)
metricsMaster <- data.table::fread(metricsMaster_path)

# lookup table mapping variable names in the survey to metricID values
metricID_lookup <- tibble::tribble(
  ~metricID, ~metricname,
  1, "TotRev_clean",
  2, "TotExp",
  3, "percent_expenses_inCashReserves",
  4, "FinanceChng_Reserves",
  5, "FinanceChng_TotExp",
  6, "FinanceChng_Salaries",
  7, "FinanceChng_Benefits",
  8, "FinanceChng_TotRent",
  9, "FinanceChng_TotTech",
  10, "GeoAreas_ServedLocal",
  11, "GeoAreas_State",
  12, "GeoAreas_Servedmultistate",
  13, "GeoAreas_National",
  14, "GeoAreas_International",
  15, "ProgDem_BelowFPL",
  16, "ProgDem_Disabled",
  17, "ProgDem_Veterans",
  18, "ProgDem_LGBTQ",
  19, "ProgDem_Foreign",
  20, "ProgDem_Latinx",
  21, "ProgDem_Black",
  22, "ProgDem_Indigenous",
  23, "ProgDem_Asian",
  24, "ProgDem_Men",
  25, "ProgDem_Women",
  26, "ProgDem_Nonbinary",
  27, "ProgDem_Children",
  28, "ProgDem_YoungAdults",
  29, "ProgDem_Adults",
  30, "ProgDem_Elders",
  31, "PplSrv_MeetDemand",
  32, "PrgSrvc_Suspend",
  33, "PrgSrvc_Amt_Srvc",
  34, "PrgSrvc_Amt_Num",
  35, "Dmnd_NxtYear",
  36, "PercentDon_Tot",
  37, "FndRaise_Cashbelow250_Chng",
  38, "FndRaise_Cashabove250_Chng",
  39, "PercentDAF_Tot",
  40, "PercentPriv_Tot",
  41, "PercentCorp_Tot",
  42, "PercentGov",
  43, "PercentEarned",
  44, "FndRaise_DAF_Rcv",
  45, "FndRaise_PFGrnt_Rcv",
  46, "FndRaise_Corp_Found_Grnt_Rcv",
  47, "FndRaise_CFGrnt_Rcv",
  50, "FndRaise_DAF_Grnt_Chng",
  51, "FndRaise_Priv_Grnt_Chng",
  52, "FndRaise_Corp_Grnt_Chng",
  53, "PrgSrvc_Amt_Fee",
  54, "FndRaise_TotExp",
  59, "PercentDem_Women_Staff",
  60, "Staff_RegVlntr",
  61, "Staff_EpsdVlntr",
  62, "PercentDem_Women_Board",
  63, "PercentDem_LGBTQ_Board",
  64, "PercentDem_Disabled_Board",
  65, "PercentDem_Young_Board",
  66, "PercentDem_ReceivedServices_Board",
  67, "PercentDem_POC_Staff",
  68, "PercentDem_LGBTQ_Staff",
  69, "PercentDem_Disabled_Staff",
  70, "PercentDem_Young_Staff",
  71, "PercentDem_ReceivedServices_Staff",
  72, "Staff_Boardmmbr",
  73, "PercentDem_POC_Board",
  74, "CEOrace_POC",
  75, "Dem_CEO_LGBTQ",
  76, "Dem_CEO_Disabled",
  77, "Dem_CEO_Under35",
  78, "BChair_POC",
  79, "Dem_BChair_LGBTQ",
  80, "Dem_BChair_Disabled",
  81, "Dem_BChair_Under35",
  82, "Staff_Fulltime",
  83, "Staff_Parttime",
  84, "CEOgender_Man",
  85, "CEOgender_Woman",
  86, "CEOgender_NB",
  87, "BChairgender_Man",
  88, "BChairgender_Woman",
  89, "BChairgender_NB",
  90, "Cash_Reserves"
)

# Deleted Metric IDs
# 55, "FndRaise_TotDigAppeal",
# 56, "FndRaise_TotDirMail",
# 57, "FndRaise_TotInPersEvent",
# 58, "FndRaise_TotVirtEvent",
# 37, "FndRaise_DnrBlw250_ratio",
# 38, "FndRaise_DnrAbv250_ratio",

# lookup table to recode responseOpt for continuous variables
responseOpt_lookup <- tibble::tribble(
  ~responseOpt_lookup, ~metricname,
  "Median total revenue", "TotRev_clean",
  "Median total expenses", "TotExp",
  "In cash reserves", "percent_expenses_inCashReserves",
  "Individual donations", "PercentDon_Tot",
  "Individual donors who gave < $250", "FndRaise_DnrBlw250_ratio",
  "Individual donors who gave ≥ $250", "FndRaise_DnrAbv250_ratio",
  "Donor-advised funds", "PercentDAF_Tot",
  "Private foundations", "PercentPriv_Tot",
  "Corporate foundations or giving programs", "PercentCorp_Tot",
  "Government funding", "PercentGov",
  "Earned revenue", "PercentEarned",
  "Regular volunteers", "Staff_RegVlntr",
  "Episodic volunteers", "Staff_EpsdVlntr",
  "Number of members", "Staff_Boardmmbr"
)

# Negative responseOpt for binary variables that should not be included in postprocessing

negative_responseOpts <- c(
  "Not serving local areas",
  "Not serving statewide",
  "Not serving multiple states",
  "Not serving nationally",
  "Not serving internationally",
  "Not serving people living in poverty",
  "Not serving people with disabilities",
  "Not serving veterans",
  "Not serving LGBTQ people",
  "Not serving immigrants",
  "Not serving Latinx/Hispanic populations",
  "Not serving Black/African American populations",
  "Not serving Indigenous/Native American and Alaska Native populations",
  "Not serving Asian populations",
  "Not serving men and boys",
  "Not serving women and girls",
  "Not serving nonbinary people",
  "Not serving children and youth",
  "Not serving young adults",
  "Not serving adults",
  "Not serving seniors",
  "Unable to meet demand",
  "Did not pause or suspend services",
  "Individual donors who gave < $250 (average %)",
  "Did not receive funding from donor-advised funds",
  "Did not receive grants from private foundations",
  "Did not receive grants from corporate foundations or giving programs",
  "Did not receive grants from community foundations",
  "CEO is not a person of color",
  "CEO is not LGBTQ",
  "CEO does not have a disability",
  "CEO is not under age 35",
  "Board chair is not a person of color",
  "Board chair is not LGBTQ",
  "Board chair does not have a disability",
  "Board chair is not under age 35",
  "CEO is not a man",
  "CEO is not a woman",
  "CEO is not nonbinary",
  "Board chair is not a man",
  "Board chair is not a woman",
  "Board chair is not nonbinary"
)

# Template containing desired outputs, excluding values for survey metrics used for validation. URL: https://observablehq.com/@jeffmacinnes/urban-nonprofit-donor-trends
# Provided by data-visualization developer Jeff MacIness [jeff@decimalpointstudio.com]
template <- data.table::fread(template_path, 
                              colClasses = list(character = c("responseOpt")))


# Metadata to merge with postprocessed data to resemble data template
template_metadata <- metricsMaster |>
  tidylog::left_join(metricID_lookup, by = "metricID") |>
  dplyr::mutate(metricID = as.integer(metricID)) |>
  dplyr::select(metricID,
                category,
                subcategory,
                dataVizType,
                metricname) |>
  as.data.frame()