project:
  type: website
  output-dir: docs

book:
  title: "NP Trends Survey Data Preparation Guide"
  author: "Thiya"
  date: "2/28/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    - 02-data-cleaning.qmd
    - 03-geocoding.qmd
    - 04-census-metadata.qmd
    - 05-anonymization.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

